### ISSUE TITLE
pickled_signal_candles' referenced before assignment

### ISSUE THREAD

**Issue by moinonin** [froggleston/freqtrade-buyreasons#5]
I got the following error when running the buy_reasons script

```
Loading backtest trades data for Strategy258btc ...
Loading all candle data: 20220101- [/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/user_data/data/binance]
Traceback (most recent call last):
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/scripts/buy_reasons.py", line 585, in <module>
    main()
  File "/home/defi/Desktop/portfolio/projects/python/crypto/freqtrade/scripts/buy_reasons.py", line 479, in main
    parallel=parallel, pickled_signal_candles=pickled_signal_candles)
UnboundLocalError: local variable 'pickled_signal_candles' referenced before assignment
```

Any workaround is appreciated!

**Comment by froggleston** [comment]
Now fixed.
